### ISSUE TITLE
STEP 2.10.0 Support ?

### ISSUE THREAD

**Issue by starkgate** [airbreather/StepperUpper#35]
STEP 2.10.0 was recently released : http://wiki.step-project.com/STEP:Guide
Are you going to update StepperUpper to support it ?

**Comment by airbreather** [comment]
Yes, I'll be working on it at some point.  It's not something I can do right this second, though.

**Comment by starkgate** [comment]
Thank you for answering :). I'll most likely be using your tool once I get back to playing Skyrim, it seems so useful I'm surprised it isn't more popular.

**Comment by airbreather** [comment]
Latest version supports 2.10.0, and I've created the pack files for Core, Extended, and *Finalize.

If there are problems with it, please let me know in a new issue.
